version: "3.8"
services:
  backend:
    build: ./backend
    container_name: finance-control-backend
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:3001
      - ConnectionStrings__Default=Data Source=/data/FinanceControl.db
      - Jwt__Key=SuaChaveSecretaForte32CaracteresAqui123456789
      - Jwt__Issuer=FinanceControl
      - Jwt__Audience=FinanceControl
      - Jwt__ExpirationSeconds=86400
    volumes:
      - finance_data:/data
    networks:
      - finance-network

  frontend:
    build: ./frontend
    container_name: finance-control-frontend
    restart: unless-stopped
    environment:
      - VITE_API_URL=/api
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - finance-network

networks:
  finance-network:
    driver: bridge

volumes:
  finance_data:
    driver: local
