version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: financecontrol_postgres
    environment:
      POSTGRES_DB: financecontrol
      POSTGRES_USER: financeuser
      POSTGRES_PASSWORD: financepass123
    ports:
      - "5432:5432"
    volumes:
      - /mnt/thiago-storage/database/finance-control:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U financeuser -d financecontrol"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - finance-network

  backend:
    build: ./backend
    container_name: finance-control-backend
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:3001
      - ConnectionStrings__PostgreSQL=Host=postgres;Database=financecontrol;Username=financeuser;Password=financepass123
      - Jwt__Key=TlSilva89SuperSecretKey2025!@#$%^&*()
      - Jwt__Issuer=FinanceControl
      - Jwt__Audience=FinanceControl
      - Jwt__ExpirationSeconds=86400
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - finance-network

  frontend:
    build: ./frontend
    container_name: finance-control-frontend
    restart: unless-stopped
    environment:
      - VITE_API_URL=/
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - finance-network

networks:
  finance-network:
    driver: bridge
